### ISSUE TITLE
Query database: sort by page timestamps doesn't work

### ISSUE THREAD

**Issue by redaLaanait** [jomei/notionapi#1]
**Thanks for developing this SDK within a few weeks after the public beta launch!**

Notion doc:

> Sorts are similar to the sorts provided in the Notion UI. Sorts operate on database properties or page timestamps and can be combined.

It seems that **Property** Field of **SortObject** should be omitted in case of an empty value, to allow sort by page timestamps

Otherwise notion API returns:

```json
{
    "object": "error",
    "status": 400,
    "code": "validation_error",
    "message": "Could not find sort property with name or id: "
}
```

**Comment by jomei** [comment]
Hi, @redaLaanait . Thank you for posting this!

Could you provide a request example for reproducing this issue, please?

**Comment by redaLaanait** [comment]
@jomei

Here the example:

```go
    token := "notion_secret_token"
	dbid := "notion_authorized_db_id"

	api := notionapi.NewClient(notionapi.Token(token))

	req := notionapi.DatabaseQueryRequest{
		Sorts: []notionapi.SortObject{
			{
				Timestamp: "last_edited_time",
				Direction: "descending",
			},
		},
	}

	resp, err := api.Database.Query(context.Background(), notionapi.DatabaseID(dbid), &req)

	log.Println(resp, err) // print: <nil> FetchDatabase err: Could not find sort property with name or id:

```

The query works as expected when: [https://github.com/redaLaanait/notionapi/commit/233f51744655a7c23be4613387d85617cca85ac4](url)

**Comment by jomei** [comment]
Wow! The fact that  `property` can be omitted is really surprising for me :) Still can't find this info in the documentation. 
Could you create a PR with this fix?

**Comment by redaLaanait** [comment]
I only found the indication that I quoted above, but still not clear
