### ISSUE TITLE
Interface for getting RichText from various blocks

### ISSUE THREAD

**Issue by pierce-m** [jomei/notionapi#165]
So many blocks have the `RichText` field, so when retrieving blocks and getting their rich text, clients have to do
```
switch t := blockWithRichText.(type) {
  case *notionapi.Heading1:
    return t.Heading1.RichText
  case *notionapi.Heading2:
    return t.Heading2.RichText
```

It would be so much better to do 
```
richText := t.GetRichText()
```

Maybe an interface such as
```
type BlockWithRichText interface {
  Block
  GetRichText() []RichText
}
```

would work?

**Comment by wulfharth7** [comment]
As far as I've seen there is no need for a new interface implementation. Instead it can be done in the **block** interface like this.
`type Block interface {
	GetType() BlockType
	GetID() BlockID
	GetObject() ObjectType
	GetCreatedTime() *time.Time
	GetLastEditedTime() *time.Time
	GetCreatedBy() *User
	GetLastEditedBy() *User
	GetHasChildren() bool
	GetArchived() bool
	GetParent() *Parent
	**GetRichText() string**
}`

I'll open a pull request soon, you may check it out and see if there is something missing.
