### ISSUE TITLE
Validation error when trying to update an image block

### ISSUE THREAD

**Issue by Lysandros-SLR** [jomei/notionapi#169]
When sending a BlockUpdateRequest with an Image a 400 is returned with a validation error. A type should not be passed in when updating an image it would seem. I tried putting in nothing for the type and got the following error

`"body failed validation: body.image.type should be not present, instead was `\"\"`."`

Tested manually and was able to update the block by not passing in a type.

**Comment by Chirab** [comment]
I think we need to add "omitempty" tag within Type 
I also have this problem when updating pdf
