### ISSUE TITLE
unsupported property type: button

### ISSUE THREAD

**Issue by manjurulhoque** [jomei/notionapi#174]
**It's very urgent**

I have been facing the issue for button property type. Initially, I guess it was from notionapi but then I checked the code and found that this error is being generated from this package itself. For this error, I am not getting the pages.

Below is my code snippet:

```
var searchRequest = notionapi.SearchRequest{
		StartCursor: startCursor,
		Sort: &notionapi.SortObject{
			Direction: notionapi.SortOrderDESC,
			Timestamp: notionapi.TimestampLastEdited,
		},
	}
	return c.NotionClient.Search.Do(context.Background(), &searchRequest)
```

what should I do here? It's very urgent.

**Comment by jomei** [comment]
Hi, @manjurulhoque !
According to [docs](https://developers.notion.com/reference/page-property-values) there are no `button` property type. So the error is correct.

Could you please provide the api response? Probably, we could figure out the button property structure without documentation

**Comment by manjurulhoque** [comment]
Hi @jomei 

Can't give you full response as it's confidential but I can give you the snippet of the response.

```
"properties": {
   //other
   "Button": {
                    "id": "gTtN",
                    "type": "button",
                    "button": {}
                },
   // other properties
   }
```

I have already fixed on a fork. I can make a PR.

**Comment by jomei** [comment]
sure, feel free to contribute

**Comment by manjurulhoque** [comment]
Created this PR https://github.com/jomei/notionapi/pull/175. Could you please check?
