### ISSUE TITLE
Parent in PageCreateRequest is invalid

### ISSUE THREAD

**Issue by Vaayne** [jomei/notionapi#25]
parent is [databaseParent](https://developers.notion.com/reference/page#database-parent) or [PageParent](https://developers.notion.com/reference/page#page-parent)

use a map format like 

```
{
    "parent": {
        "database_id": "abcd"
    }
}
```
Current in sdk is 

```
{
    "parent": {
        "type": "database_id",
        "database_id": "abcd"
    }
}
```

**Comment by jomei** [comment]
Hey, @Vaayne !
I didn't catch the point of this issue.
current `Parent` struct is 
```
type Parent struct {
	Type       ParentType `json:"type,omitempty"`
	PageID     PageID     `json:"page_id,omitempty"`
	DatabaseID DatabaseID `json:"database_id,omitempty"`
}
```

so you can easily omit any of provided fields. If you don't need the `type` property in your request, just left it empty.

Could you provide more information about this problem?

**Comment by Vaayne** [comment]
@jomei   I think it is Notion's bug.

https://developers.notion.com/reference/post-page
The example is different from the struct. And **the one in example worked**.

**Comment by jomei** [comment]
Still don't understand.
Could you please provide an example of a valid request or response that doesn't cover by current structure?

**Comment by jomei** [comment]
`type` is required for parsing responses. For requests, you can leave this property empty and everything will be OK, right?

**Comment by Vaayne** [comment]
> `type` is required for parsing responses. For requests, you can leave this property empty and everything will be OK, right?

Right.
