### ISSUE TITLE
Supports update page's icon and cover

### ISSUE THREAD

**Issue by SakuraDon99** [jomei/notionapi#56]
HiHi master, thanks for your SDK!

The official API supports updating the icon and cover of the page. Could you update the SDK to support this function ?

**Comment by zhangzheng1214** [comment]
> HiHi master, thanks for your SDK!
> 
> The official API supports updating the icon and cover of the page. Could you update the SDK to support this function ?

I have the same issue, too

**Comment by jomei** [comment]
Hi @SakuraDon99 and @zhangzheng1214. Fixed!

**Comment by zhangzheng1214** [comment]
> Hi @SakuraDon99 and @zhangzheng1214. Fixed!

Thanks~~~
