### ISSUE TITLE
Need way to retrieve Page Content

### ISSUE THREAD

**Issue by boltlessengineer** [jomei/notionapi#57]
According to [this Notion Wiki page](https://developers.notion.com/docs/working-with-page-content#reading-blocks-from-a-page), Page also uses [retrieve block children](https://developers.notion.com/reference-link/get-block-children) endpoint.

Currently, `BlockService.GetChildren()` only uses `BlockID` type for `block_id` parameter, and `PageService` doesn't have `GetChildren()` method. Then, How can I retrieve Page Content? Is there any way to do this?

I think adding `GetChildren()` method to `PageService` may make this work.

**Comment by jomei** [comment]
Hi,@boltlessegineer!
I don't know for sure and unfortunately can't check it right now, but, as I know, you can pass `PageID` as `BlockID` to `BlockService.GetChildren().

Could you please try it this way and tell me the result?

**Comment by boltlessengineer** [comment]
Hi, thanks for the reply.
Unfortunately it was simply my fault. As I am still learning golang, I just did not understand the concept of type conversion in golang accurately.
I'm closing Issue.
