### ISSUE TITLE
Unset date property

### ISSUE THREAD

**Issue by chapterjason** [jomei/notionapi#71]
Currently, it isn't possible to unset a date property.
Making it a pointer works.

https://github.com/jomei/notionapi/blob/24b668e12f1ce5a1309e1b729857696a9644cee7/property.go#L110

I've created a small workaround that works:

```go
type EmptyDateProperty struct {
	ID   notionapi.ObjectID     `json:"id,omitempty"`
	Type notionapi.PropertyType `json:"type,omitempty"`
	Date *notionapi.DateObject  `json:"date"`
}

func (p EmptyDateProperty) GetType() notionapi.PropertyType {
	return p.Type
}

// [...]

updates["Completed At"] = &EmptyDateProperty{
    ID:   completedAtProperty.ID,
    Type: completedAtProperty.Type,
    Date: nil,
}

// [...]
```

**Comment by jomei** [comment]
Hi, @chapterjason !
Could you please provide an example use case where EmptyProperty is needed?

**Comment by chapterjason** [comment]
Hey @jomei 

Sure,, I have a small task board with the following properties

- Choice `State` with the values `Blocked`, `In Progress` and `Done`
- Date `Completed At`

I've built a daemon which sets makest the following changes:
- if `state == "Done" && completedAt == nil` set `Completed At` to now 
- if `state != "Done" && completedAt != nil` set `Completed At` to empty or clear as it is called in the UI of notion.

![image](https://user-images.githubusercontent.com/1337562/166643136-461adcbf-1aad-44f1-9b2b-564a920dc60e.png)
