### ISSUE TITLE
Is there a way to update code block caption?

### ISSUE THREAD

**Issue by ariary** [jomei/notionapi#87]
`BlockUpdateRequest` struct has a field `Code` but the ``Code`struct does not have `Caption` field. rather it is the `CodeBlock` that has the  `Caption` field.

My question is: is there a way to update CodeBlock instead of Code thus making the caption update possible?

**Comment by jomei** [comment]
Hey! It seems like the `Caption ` field is misplaced by some reason. I'll move it into the `Code` object.
