### ISSUE TITLE
Support nested compound filters

### ISSUE THREAD

**Issue by harryzcy** [jomei/notionapi#89]
Per [notion reference](https://developers.notion.com/reference/post-database-query-filter#compound-filter-object), the compound filters can be nested. Currently, `CompoundFilter` is defined as `map[FilterOperator][]PropertyFilter`, thus only property filters are allowed inside of a compound filter.

It's better to have a `Filter` interface, and let both `CompoundFilter` and `PropertyFilter` to implement the interface.

I can try to do it in the coming days.

**Comment by jomei** [comment]
Hi, @harryzcy!
Looks like this issue is fixed already in #86. 
Should be released soon

**Comment by harryzcy** [comment]
Closing as #86 is merged
